# Generated by Django 3.1.1 on 2021-05-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cifir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='cover',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalog',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
