# Generated by Django 3.1.1 on 2021-05-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cifir', '0002_auto_20210513_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='catalog',
        ),
    ]
