# Generated by Django 3.1.1 on 2021-05-13 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cifir', '0003_remove_library_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
