# Generated by Django 3.1.1 on 2021-05-14 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cifir', '0005_auto_20210513_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
